version: '3'
services:
  express-api-es6-starter:
    build: .
    volumes:
      - .env.docker:/app/.env
    ports:
      - '8848:8848'
    entrypoint: /bin/sh
    command: -c "sleep 5 && yarn migrate && yarn seed && yarn start:dev"
    depends_on:
      - pg
      - pg_test
    links:
      - pg
      - pg_test
  pg:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=express
  pg_test:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=express_test
